spring:
  application:
    name: workload-service

logging:
  pattern:
    level: "%5p [txId=%X{transactionId}]"

server:
  port: 8082
  servlet:
    context-path: /workload-service

api:
  base-path: /api/v1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}