spring:
  application:
    name: workload-service
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}
  spring:
    data:
      mongodb:
        uri: ${MONGODB_URI:}
  jms:
    pub-sub-domain: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

activemq:
  destination:
    trainer-workload: trainer-workload-queue
    trainer-workload-dlq: trainer-workload-dlq
  redelivery:
    max-redeliveries: 3

jwt:
  secret: ${JWT_SECRET}

logging:
  pattern:
    level: "%5p [txId=%X{transactionId}]"

server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /workload-service

api:
  base-path: /api/v1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:}
  instance:
    prefer-ip-address: true