spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        type:
          preferred_boolean_jdbc_type: TINYINT

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.gym.crm: INFO